#!C:\Users\arnau\Documents\3A\Projet IA\Projet_IA_2526\.envSon\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
